spring.application.name=training-axoniq-5

spring.datasource.url=jdbc:h2:mem:projections;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

#axon.update-check.disabled=true

axoniq.platform.credentials=${AXONIQ_PLATFORM_CREDENTIALS}
#If you can't connect to Axoniq platform, a license file will be required to use Axoniq Framework.
#axoniq.license.file=./axoniq.license
